# Generated by Django 5.2.3 on 2025-12-11 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_order_user_id_order_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=70),
        ),
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='food.food'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.category'),
        ),
    ]
