# Generated by Django 5.2.3 on 2025-12-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_orderitem_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('out for delivery', 'Out for delivery'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
