# Generated by Django 5.2.9 on 2026-01-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_order_unique_pending_order_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
