# Generated by Django 5.2.9 on 2026-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_order_phone_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('out for delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
