# Generated by Django 5.2.9 on 2026-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
