# Generated by Django 5.2.9 on 2026-04-05 23:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_category_slug_alter_food_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='logo',
            new_name='profile_photo',
        ),
        migrations.AlterField(
            model_name='food',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='food.vendor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='food.order'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('business_name'), name='unique_business_name_ci'),
        ),
    ]
