# Generated by Django 5.2.9 on 2026-04-07 18:55

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_rename_logo_vendor_profile_photo_alter_food_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('vendor'), name='unique_vendor_food_name_ci'),
        ),
    ]
